# Generated by Django 5.0.6 on 2025-11-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('name_of_institution', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('IADVL_membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_preference', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='accompayingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('relation_to_delegate', models.CharField(max_length=100)),
                ('meal_preference', models.CharField(max_length=50)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompanying_persons', to='registration.registereduser')),
            ],
        ),
    ]
