# Generated by Django 5.0.6 on 2025-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
